apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test2
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: test
  source:
    repoURL: 'https://github.com/shashanklmurthy/k8s-argocd-test.git'
    path: dep2
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argo-test
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
